app:
    resource: '@AppBundle/Controller/'
    type: annotation

api:
    type: rest
    prefix: /api
    resource: "@AppBundle/Controller/Api"
    options:
        expose: true

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
